version: '3.7'

services:
  backend:
    image: fruitshop
    expose:
      - "80"
    ports:
      - "8080:80"
  example:
    container_name: fruitshop-ui
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '4200:4200'